# Generated by Django 5.1.5 on 2025-02-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SWIFTAccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('country_of_operation', models.CharField(max_length=100)),
                ('account_number', models.CharField(help_text='Account Number', max_length=34)),
                ('swift_service_requested', models.CharField(choices=[('MT103', 'Payment Initiation (SWIFT MT103)'), ('MT202', 'Fund Transfer Services (SWIFT MT202)'), ('FX', 'Foreign Exchange Transactions'), ('SEC', 'Securities Settlements'), ('OTHER', 'Other')], default='MT103', max_length=10)),
                ('other_service_description', models.CharField(blank=True, help_text="Describe if 'Other' service is selected", max_length=255, null=True)),
                ('primary_contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('country_of_incorporation', models.CharField(max_length=100)),
                ('legal_entity_identifier', models.CharField(blank=True, help_text='Optional LEI for compliance', max_length=20, null=True)),
                ('kyc_aml_documents', models.FileField(blank=True, help_text='Upload KYC/AML document', null=True, upload_to='kyc_documents/')),
                ('authorized_signatory_name', models.CharField(max_length=255)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
    ]
